; Generated by Calypsi ISO C compiler for 6502

            .rtmodel version,"1"
            .rtmodel codeModel,"plain"
            .rtmodel core,"6502"
            .rtmodel target,"plain"
            .extern _Vfp
            .extern _Vsp
            .extern _Zp
;  #include "../m65script_fileio.h"
;
;  void test(uint8_t test){
            .section code,text
            .public test
test:
;      return;
;  }
            rts
;
;  int m65script_load(char* buffer, int size , char* filename,   uint8_t device ){
            .section code,text
            .public m65script_load
m65script_load:
;      test(device);
            lda     zp:_Zp+6
            sta     zp:_Zp
            lda     zp:_Zp+7
            sta     zp:_Zp+1
            jsr     test
;      return 1024;
            lda     #0
            sta     zp:_Zp
            lda     #4
            sta     zp:_Zp+1
;  }
            rts

